# name: Build and Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         persist-credentials: false

#     - name: Use Node.js '12.x'
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'
#     - name: Install and Build 🔧
#       run: |
#         npm install
#         npm run export
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACTION_DEPLOYMENT }}
#         BRANCH: gh-pages
#         FOLDER: __sapper__/export/sapper
#         CLEAN: true
name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js '12.x'
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and Build 🔧
      run: |
        npm install
        npm run export
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export
          publish_branch: gh-pages
          github_token: ${{ secrets.ACTION_DEPLOYMENT }}